COLORS = %w[ DEEPSKYBLUE TURQUOISE TEAL DARKBLUE DARKRED LIGHTSALMON RED PINK
             HOTPINK ORANGE YELLOW PURPLE VIOLET LIME SEAGREEN DARKGREEN TAN
             BROWN DARKSLATEGRAY DARKGRAY ].freeze