COLORS = %w[DARKRED LIGHTSALMON RED PINK HOTPINK ORANGE YELLOW PURPLE VIOLET
             LIME SEAGREEN DARKGREEN TEAL TURQUOISE DEEPSKYBLUE DARKBLUE TAN
             BROWN DARKSLATEGRAY DARKGRAY].freeze